---

info:
  description: Training configuration repo
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://username:password@service-registry-mwebb.cfapps.io/eureka 
      
system:
  shared:
    test-property: this is a test property
avm:
  shared:
    avm-property: this is avm specific property
  
      
corelogic: this is our value
core2: Here is another CIS testing property
encryptedProp: '{cipher}AQCmZscgWYzcMrzzY6E+nJB5ZrP82SDNZ8LgzdF6GqJh72zU4zzaKU/P2u4oPFMo53tNXB0IcbLkfglnm6pyD2FPAoBvmiJWD5QKZCMT3cw2fm80sY9gkZM1+6es6pPmq3ZuvLjf+TiLX6bbTmfPRx3VKzY6UU/D74mwlh+N0cBNkoiFsJd0QCtggrZsWCcf3qqYkLMoohXO/7PXpqpfydYDEZ+cQlP3y3hBckIhGxG5l4Ai53aW5MPEewWT1TZm9nWXVdIknTyYqulce+59lfESs/7/ixp2vHtRjMbRx0iDqDeBnf2skJHcNjPr1fEfLaFycnXyKiJgy5/QrmFvHxZIfx2hNrWZuWWnyqtYvV2vouW727D9/oi+ZHIYNYv9tgM='
